version: "2"

services:
  app:
    depends_on:
      - db
    image: registry.gitlab.com/diazzzu/angimehubbackend
    ports:
      - "80:8080"
    restart: on-failure

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: secret
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
    volumes:
      - my_data_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

volumes:
  my_data_volume: